---
# Role to deploy test modules
- name: Check test module registration
  uri:
    url: http://localhost:9130/_/proxy/modules/{{ item }}
    status_code: 200, 404
  with_items:
    - test-basic
    - test-auth
  register: test_reg_status

- name: Register test modules
  uri:
    url: http://localhost:9130/_/proxy/modules
    method: POST
    body_format: json
    body: "{{ lookup('template', item.template) }}"
    status_code: 201
  when: test_reg_status.results[item.index].status == 404
  with_items:
    - { template: test-basic.json.j2, index: 0 }
    - { template: test-auth.json.j2, index: 1 }

- name: Check test module deployment
  uri:
    url: http://localhost:9130/_/discovery/modules/{{ item }}
    status_code: 200, 404
  with_items:
    - test-basic
    - test-auth
  register: test_deploy_status

- name: Deploy test modules
  uri:
    url: http://localhost:9130/_/discovery/modules
    method: POST
    body_format: json
    body: '{ "srvcId" : "{{ item.module }}", "nodeId" : "localhost" }'
    status_code: 201
  when: test_reg_status.results[item.index].status == 404
  with_items:
    - { module: test-basic, index: 0 }
    - { module: test-auth, index: 1 }

- name: Check testlib tenant
  uri:
    url: http://localhost:9130/_/proxy/tenants/testlib
    status_code: 200, 404
  register: testlib_status

- name: Create testlib tenant
  uri:
    url: http://localhost:9130/_/proxy/tenants
    method: POST
    body_format: json
    body: '{ "id" : "testlib", "name" : "Test Library", "description" : "Our Own Test Library" }'
    status_code: 201
  when: testlib_status.status == 404
  
- name: Enable test modules for testlib
  uri:
    url: http://localhost:9130/_/proxy/tenants/testlib/modules
    method: POST
    body_format: json
    body: '{ "id" : "{{ item }}" }'
  with_items:
    - test-basic
    - test-auth
